### ISSUE TITLE
Final checklist

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser-hsr-sa#18]
- [x] Make sure all issues are closed here
- [x] Make sure no FIXMEs are remaining
- [x] Review docs against S. Keller checklist
- [x] Make sure last language feedback is incorporated
- [x] Update time tracking if needed
- [x] Make sure brochure text is accepted at https://abstract.hsr.ch/
- [x] Print and proofread
- [x] Review layout
  - [x] Check LaTeX warnings such as over-/underfull hboxes (turn on draft mode)
  - [x] Image resolution sufficient?
- [x] Create archive folder:
  - [x] Eigenständigkeitserklärung (**unterschrieben**)
  - [x] Urheber- und Nutzungsrechte (**unterschrieben**)
  - [x] Poster
  - [x] ~~Plain-Text abstract~~
  - [x] PDF
  - [x] Einverständniserklärung für Publikation (**unterschrieben**)
  - [x] Brochure
  - [x] Sitzungsprotokolle
  - [x] Copy of qutebrowser/qutebrowser repo
  - [x] Copy of qutebrowser/qutebrowser-hsr-sa repo
  - [x] Aufgabenstellung
- [x] Upload to https://archiv-i.hsr.ch/
  - [x] ZIP archive of archive folder
  - [x] Eigenständigkeitserklärung
  - [x] Urheber- und Nutzungsrechte
  - [x] Poster
  - [x] Plain-Text abstract
  - [x] PDF
  - [x] Einverständniserklärung für Publikation
- [x] USB stick with archive folder -> S. Keller
- [x] Send PDF to ZKB for printing
